# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build_project
  jobs:
    - job: Build
      displayName: Bild the asp.net project and test project
      pool:
        vmImage: ubuntu-latest
      steps:
      - task: DotNetCoreCLI@2
        displayName: Build the project
        inputs:
          command: build

    - job: Test
      displayName: Test the asp.net project and test project
      pool:
        vmImage: ubuntu-latest
      steps:
      - task: DotNetCoreCLI@2
        displayName: Build the project
        inputs:
          command: test
          

- stage: Build_Image
  displayName: Build image
  dependsOn: Build_project
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/src/TaskTracker.Api/Dockerfile'
        tags: |
          $(tag)
